document.write('<table id="menu"><tr><td>',
 '<ul id="fabmenu" class="topmenu">',
 '<li class="topfirst">',
 '<a href="index.html" title="" style="width:150px;">Home</a>',
 '</li>',
 '<li class="topmenu">',
 '<a href="#" title="" style="width:150px;"><span>Fine Arts Board</span></a>',
 '<ul>',
 '<li class="subfirst">',
 '<a href="history.html" title="" style="width:150px;">History</a>',
 '</li>',
 '<li>',
 '<a href="members.html" title="">Current Members</a>',
 '</li>',
 '<li>',
 '<a href="angels.html" title="">Angels of the Fine Arts</a>',
 '</li>',
 '</ul>',
 '</li>',
 '<li class="topmenu">',
 '<a href="#" title="" style="width:150px;"><span>Seasons &amp; Celebrations</span></a>',
 '<ul>',
 '<li class="subfirst">',
 '<a href="2013-14.html" title="" style="width:150px;">2013-14 Final Season</a>',
 '</li>',
 '<li>',
 '<a href="2012-13.html" title="">2012-13 Season</a>',
 '</li>',
 '<li>',
 '<a href="2011-12.html" title="">2011-12 Season</a>',
 '</li>',
 '<li>',
 '<a href="2010-11.html" title="">2010-11 Season</a>',
 '</li>',
 '<li>',
 '<a href="25th.html" title="">25th Anniversary</a>',
 '</li>',
 '</ul>',
 '</li>',
 '<li class="topmenu">',
 '<a href="#" title="" style="width:150px;">Facilities</a>',
 '<ul>',
 '<li class="subfirst">',
 '<a href="sanctuary.html" title="" style="width:150px;">Sanctuary</a>',
 '</li>',
 '<li>',
 '<a href="moeller.html" title="">M&ouml;ller Organ</a>',
 '</li>',
 '<li>',
 '<a href="piano.html" title="">Piano</a>',
 '</li>',
 '<li>',
 '<a href="fireside.html" title="">Fireside Room</a>',
 '</li>',
 '</ul>',
 '</li>',
 '<li class="topmenu">',
 '<a href="carillon.html" title="" style="width:150px;"><span>The Children&#8217;s Carillon</span></a>',
 '</li>',
 '<li class="toplast">',
 '<a href="http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=307+Kingsbury+Avenue,+La+Porte,+IN&sll" target="_blank" title="" style="width:150px;"><span>Location / Map</span></a>',
 '</li>',
 '</ul>',
 '</td>',
 '</tr>',
 '</table>');